"""Initial schema baseline.

Revision ID: 20260521_01
Revises:
Create Date: 2026-05-21 00:00:00
"""

from __future__ import annotations

from alembic import op

# revision identifiers, used by Alembic.
revision = "20260521_01"
down_revision = None
branch_labels = None
depends_on = None


UPGRADE_STATEMENTS = (
    """
    CREATE TABLE allocationalert (
        id INTEGER NOT NULL,
        alert_key VARCHAR NOT NULL,
        alert_type VARCHAR NOT NULL,
        severity VARCHAR NOT NULL,
        state VARCHAR NOT NULL,
        escalation_level VARCHAR NOT NULL,
        title VARCHAR NOT NULL,
        message VARCHAR,
        count INTEGER NOT NULL,
        recurrence_count INTEGER NOT NULL,
        first_seen_at DATETIME NOT NULL,
        last_seen_at DATETIME NOT NULL,
        last_evaluated_at DATETIME NOT NULL,
        acknowledged_at DATETIME,
        acknowledged_by VARCHAR,
        resolved_at DATETIME,
        resolved_by VARCHAR,
        escalated_at DATETIME,
        related_intent_ids JSON,
        related_cycle_ids JSON,
        related_execution_ids JSON,
        details JSON,
        created_at DATETIME NOT NULL,
        updated_at DATETIME NOT NULL,
        PRIMARY KEY (id)
    )
    """,
    "CREATE INDEX ix_allocationalert_updated_at_desc ON allocationalert (updated_at DESC)",
    "CREATE INDEX ix_allocationalert_escalation_level ON allocationalert (escalation_level)",
    "CREATE INDEX ix_allocationalert_last_seen_at ON allocationalert (last_seen_at)",
    "CREATE INDEX ix_allocationalert_updated_at ON allocationalert (updated_at)",
    "CREATE UNIQUE INDEX ix_allocationalert_alert_key ON allocationalert (alert_key)",
    "CREATE INDEX ix_allocationalert_state_updated_at ON allocationalert (state, updated_at DESC)",
    "CREATE INDEX ix_allocationalert_state ON allocationalert (state)",
    "CREATE INDEX ix_allocationalert_first_seen_at ON allocationalert (first_seen_at)",
    "CREATE INDEX ix_allocationalert_severity_updated_at ON allocationalert (severity, updated_at DESC)",
    "CREATE INDEX ix_allocationalert_last_evaluated_at ON allocationalert (last_evaluated_at)",
    "CREATE INDEX ix_allocationalert_severity ON allocationalert (severity)",
    "CREATE INDEX ix_allocationalert_alert_type ON allocationalert (alert_type)",
    """
    CREATE TABLE domain_events (
        id INTEGER NOT NULL,
        created_at DATETIME NOT NULL,
        event_type VARCHAR NOT NULL,
        category VARCHAR NOT NULL,
        severity VARCHAR NOT NULL,
        error_type VARCHAR,
        source VARCHAR NOT NULL,
        correlation_id VARCHAR,
        runtime_id VARCHAR,
        strategy_name VARCHAR,
        instrument VARCHAR,
        position_id INTEGER,
        trade_id INTEGER,
        execution_id INTEGER,
        actor_type VARCHAR,
        actor_id VARCHAR,
        title VARCHAR NOT NULL,
        message VARCHAR,
        payload_json JSON,
        PRIMARY KEY (id)
    )
    """,
    "CREATE INDEX ix_domain_events_position_id ON domain_events (position_id)",
    "CREATE INDEX ix_domain_events_error_type_created_at ON domain_events (error_type, created_at DESC)",
    "CREATE INDEX ix_domain_events_error_type ON domain_events (error_type)",
    "CREATE INDEX ix_domain_events_trade_id ON domain_events (trade_id)",
    "CREATE INDEX ix_domain_events_strategy_created_at ON domain_events (strategy_name, created_at DESC)",
    "CREATE INDEX ix_domain_events_source ON domain_events (source)",
    "CREATE INDEX ix_domain_events_instrument_created_at ON domain_events (instrument, created_at DESC)",
    "CREATE INDEX ix_domain_events_event_type ON domain_events (event_type)",
    "CREATE INDEX ix_domain_events_execution_id ON domain_events (execution_id)",
    "CREATE INDEX ix_domain_events_correlation_id ON domain_events (correlation_id)",
    "CREATE INDEX ix_domain_events_actor_type ON domain_events (actor_type)",
    "CREATE INDEX ix_domain_events_runtime_id ON domain_events (runtime_id)",
    "CREATE INDEX ix_domain_events_category_created_at ON domain_events (category, created_at DESC)",
    "CREATE INDEX ix_domain_events_created_at ON domain_events (created_at)",
    "CREATE INDEX ix_domain_events_created_at_desc ON domain_events (created_at DESC)",
    "CREATE INDEX ix_domain_events_actor_id ON domain_events (actor_id)",
    "CREATE INDEX ix_domain_events_strategy_name ON domain_events (strategy_name)",
    "CREATE INDEX ix_domain_events_severity_created_at ON domain_events (severity, created_at DESC)",
    "CREATE INDEX ix_domain_events_category ON domain_events (category)",
    "CREATE INDEX ix_domain_events_correlation_created_at ON domain_events (correlation_id, created_at DESC)",
    "CREATE INDEX ix_domain_events_instrument ON domain_events (instrument)",
    "CREATE INDEX ix_domain_events_severity ON domain_events (severity)",
    """
    CREATE TABLE operatorcontrolstate (
        id INTEGER NOT NULL,
        autonomous_control_override BOOLEAN,
        override_reason VARCHAR,
        updated_at DATETIME NOT NULL,
        PRIMARY KEY (id)
    )
    """,
    "CREATE INDEX ix_operatorcontrolstate_autonomous_control_override ON operatorcontrolstate (autonomous_control_override)",
    """
    CREATE TABLE promotion_request (
        id INTEGER NOT NULL,
        instrument VARCHAR NOT NULL,
        source VARCHAR NOT NULL,
        reason VARCHAR NOT NULL,
        score FLOAT NOT NULL,
        status VARCHAR NOT NULL,
        requested_at DATETIME NOT NULL,
        expires_at DATETIME,
        market_status VARCHAR,
        tradable BOOLEAN,
        requested_frequency VARCHAR,
        updated_at DATETIME NOT NULL,
        PRIMARY KEY (id)
    )
    """,
    "CREATE INDEX ix_promotion_request_status ON promotion_request (status)",
    "CREATE INDEX ix_promotion_request_status_requested_at ON promotion_request (status, requested_at DESC)",
    "CREATE INDEX ix_promotion_request_source ON promotion_request (source)",
    "CREATE INDEX ix_promotion_request_requested_at ON promotion_request (requested_at)",
    "CREATE INDEX ix_promotion_request_instrument ON promotion_request (instrument)",
    """
    CREATE TABLE generatedreviewrecord (
        id INTEGER NOT NULL,
        review_type VARCHAR NOT NULL,
        scope JSON,
        generated_at DATETIME NOT NULL,
        facts_payload JSON,
        derived_observations JSON,
        possible_contributors JSON,
        warnings JSON,
        supporting_metrics JSON,
        ai_summary JSON,
        prompt_version VARCHAR NOT NULL,
        provider VARCHAR,
        model VARCHAR,
        raw_model_response VARCHAR,
        generation_mode VARCHAR NOT NULL,
        PRIMARY KEY (id)
    )
    """,
    "CREATE INDEX ix_generatedreviewrecord_review_type ON generatedreviewrecord (review_type)",
    "CREATE INDEX ix_generatedreviewrecord_generation_mode ON generatedreviewrecord (generation_mode)",
    "CREATE INDEX ix_generatedreviewrecord_generated_at ON generatedreviewrecord (generated_at)",
    """
    CREATE TABLE strategydeployment (
        id INTEGER NOT NULL,
        strategy_name VARCHAR NOT NULL,
        governance_id INTEGER,
        deployment_key VARCHAR NOT NULL,
        state VARCHAR NOT NULL,
        selected_profile VARCHAR,
        selected_instrument VARCHAR,
        selected_asset_class VARCHAR,
        control_mode VARCHAR NOT NULL,
        suitability_score FLOAT,
        suitability_reason VARCHAR,
        selected_profile_parameters JSON,
        profile_selected_at DATETIME,
        profile_change_reason VARCHAR,
        blocked_reason VARCHAR,
        degraded_reason VARCHAR,
        last_restart_reason VARCHAR,
        last_evaluated_at DATETIME,
        last_state_changed_at DATETIME NOT NULL,
        last_deployed_at DATETIME,
        operator_intervention_state VARCHAR,
        open_risk_management_state VARCHAR NOT NULL,
        open_risk_management_reason VARCHAR,
        deployment_metadata JSON,
        created_at DATETIME NOT NULL,
        updated_at DATETIME NOT NULL,
        PRIMARY KEY (id)
    )
    """,
    "CREATE INDEX ix_strategydeployment_state ON strategydeployment (state)",
    "CREATE INDEX ix_strategydeployment_strategy_name ON strategydeployment (strategy_name)",
    "CREATE INDEX ix_strategydeployment_governance_id ON strategydeployment (governance_id)",
    "CREATE INDEX ix_strategydeployment_selected_asset_class ON strategydeployment (selected_asset_class)",
    "CREATE UNIQUE INDEX ix_strategydeployment_deployment_key ON strategydeployment (deployment_key)",
    "CREATE INDEX ix_strategydeployment_open_risk_management_state ON strategydeployment (open_risk_management_state)",
    "CREATE INDEX ix_strategydeployment_selected_instrument ON strategydeployment (selected_instrument)",
    "CREATE INDEX ix_strategy_deployment_state_strategy ON strategydeployment (state, strategy_name, updated_at DESC)",
    "CREATE INDEX ix_strategydeployment_control_mode ON strategydeployment (control_mode)",
    """
    CREATE TABLE strategyfamilygovernance (
        id INTEGER NOT NULL,
        strategy_name VARCHAR NOT NULL,
        approval_state VARCHAR NOT NULL,
        autonomous_operation_allowed BOOLEAN NOT NULL,
        emergency_stop BOOLEAN NOT NULL,
        approved_asset_classes JSON,
        approved_instruments JSON,
        approved_profile_names JSON,
        max_concurrent_deployments INTEGER NOT NULL,
        notes VARCHAR,
        created_at DATETIME NOT NULL,
        updated_at DATETIME NOT NULL,
        PRIMARY KEY (id)
    )
    """,
    "CREATE INDEX ix_strategyfamilygovernance_approval_state ON strategyfamilygovernance (approval_state)",
    "CREATE UNIQUE INDEX ix_strategyfamilygovernance_strategy_name ON strategyfamilygovernance (strategy_name)",
    """
    CREATE TABLE strategyruntimestate (
        id INTEGER NOT NULL,
        runtime_id VARCHAR NOT NULL,
        strategy_name VARCHAR NOT NULL,
        strategy_version VARCHAR NOT NULL,
        instrument VARCHAR NOT NULL,
        parameters JSON,
        status VARCHAR NOT NULL,
        recovery_state VARCHAR NOT NULL,
        recovery_reason VARCHAR,
        started_at DATETIME NOT NULL,
        stopped_at DATETIME,
        last_heartbeat_at DATETIME,
        last_price_seen FLOAT,
        last_price_seen_at DATETIME,
        current_position_broker_reference VARCHAR,
        control_mode VARCHAR DEFAULT 'MANUAL' NOT NULL,
        runtime_mode VARCHAR DEFAULT 'NORMAL' NOT NULL,
        deployment_id INTEGER,
        active_profile_name VARCHAR,
        auto_resume BOOLEAN NOT NULL,
        startup_context JSON,
        strategy_state_snapshot JSON,
        created_at DATETIME NOT NULL,
        updated_at DATETIME NOT NULL,
        PRIMARY KEY (id)
    )
    """,
    "CREATE INDEX ix_strategyruntimestate_instrument ON strategyruntimestate (instrument)",
    "CREATE INDEX ix_strategyruntimestate_strategy_name ON strategyruntimestate (strategy_name)",
    "CREATE INDEX ix_strategyruntimestate_runtime_mode ON strategyruntimestate (runtime_mode)",
    "CREATE INDEX ix_strategyruntimestate_recovery_state ON strategyruntimestate (recovery_state)",
    "CREATE INDEX ix_strategyruntimestate_deployment_id ON strategyruntimestate (deployment_id)",
    "CREATE INDEX ix_strategyruntimestate_active_profile_name ON strategyruntimestate (active_profile_name)",
    "CREATE INDEX ix_strategyruntimestate_control_mode ON strategyruntimestate (control_mode)",
    "CREATE INDEX ix_strategyruntimestate_status ON strategyruntimestate (status)",
    "CREATE UNIQUE INDEX ix_strategyruntimestate_runtime_id ON strategyruntimestate (runtime_id)",
    "CREATE INDEX ix_strategyruntimestate_current_position_broker_reference ON strategyruntimestate (current_position_broker_reference)",
    """
    CREATE TABLE trade (
        id INTEGER NOT NULL,
        trade_intent_id INTEGER,
        strategy_name VARCHAR NOT NULL,
        family_name VARCHAR,
        broker_reference VARCHAR,
        close_broker_reference VARCHAR,
        instrument VARCHAR NOT NULL,
        direction VARCHAR NOT NULL,
        size FLOAT NOT NULL,
        open_price FLOAT NOT NULL,
        close_price FLOAT NOT NULL,
        open_time DATETIME NOT NULL,
        close_time DATETIME NOT NULL,
        pnl FLOAT NOT NULL,
        entry_risk_amount FLOAT,
        risk_truth_confidence VARCHAR,
        close_execution_source VARCHAR,
        r_multiple FLOAT,
        outcome VARCHAR,
        reason VARCHAR,
        account_type VARCHAR NOT NULL,
        created_at DATETIME NOT NULL,
        PRIMARY KEY (id)
    )
    """,
    "CREATE INDEX ix_trade_family_name ON trade (family_name)",
    "CREATE INDEX ix_trade_broker_reference ON trade (broker_reference)",
    "CREATE INDEX ix_trade_close_broker_reference ON trade (close_broker_reference)",
    "CREATE INDEX ix_trade_trade_intent_id ON trade (trade_intent_id)",
    "CREATE INDEX ix_trade_close_execution_source ON trade (close_execution_source)",
    """
    CREATE TABLE position (
        id INTEGER NOT NULL,
        trade_intent_id INTEGER,
        strategy_name VARCHAR NOT NULL,
        family_name VARCHAR,
        broker_reference VARCHAR,
        instrument VARCHAR NOT NULL,
        direction VARCHAR NOT NULL,
        size FLOAT NOT NULL,
        open_price FLOAT NOT NULL,
        close_price FLOAT,
        open_time DATETIME NOT NULL,
        close_time DATETIME,
        pnl FLOAT,
        current_price FLOAT,
        unrealized_pnl FLOAT,
        risk_percent FLOAT,
        entry_risk_amount FLOAT,
        risk_truth_confidence VARCHAR,
        reason VARCHAR,
        manual_override BOOLEAN NOT NULL,
        account_type VARCHAR NOT NULL,
        is_open BOOLEAN NOT NULL,
        broker_sync_status VARCHAR NOT NULL,
        close_execution_source VARCHAR,
        broker_open_confirmed_at DATETIME,
        broker_closed_confirmed_at DATETIME,
        last_reconciled_at DATETIME,
        created_at DATETIME NOT NULL,
        PRIMARY KEY (id)
    )
    """,
    "CREATE INDEX ix_position_broker_sync_status ON position (broker_sync_status)",
    "CREATE INDEX ix_position_instrument ON position (instrument)",
    "CREATE INDEX ix_position_trade_intent_id ON position (trade_intent_id)",
    "CREATE INDEX ix_position_close_execution_source ON position (close_execution_source)",
    "CREATE INDEX ix_position_broker_reference ON position (broker_reference)",
    "CREATE INDEX ix_position_family_name ON position (family_name)",
    """
    CREATE TABLE execution (
        id INTEGER NOT NULL,
        trade_intent_id INTEGER,
        strategy_name VARCHAR NOT NULL,
        instrument VARCHAR NOT NULL,
        phase VARCHAR NOT NULL,
        status VARCHAR NOT NULL,
        client_request_id VARCHAR,
        broker_reference VARCHAR,
        local_position_id INTEGER,
        local_trade_id INTEGER,
        signal_time DATETIME NOT NULL,
        submitted_at DATETIME,
        acknowledged_at DATETIME,
        completed_at DATETIME,
        last_transition_at DATETIME NOT NULL,
        requested_size FLOAT,
        filled_size FLOAT,
        requested_price FLOAT,
        average_fill_price FLOAT,
        intended_risk_amount FLOAT,
        submitted_risk_amount FLOAT,
        fill_derived_risk_amount FLOAT,
        risk_truth_confidence VARCHAR,
        reason VARCHAR,
        error_code VARCHAR,
        error_message VARCHAR,
        requires_manual_review BOOLEAN NOT NULL,
        details JSON,
        created_at DATETIME NOT NULL,
        updated_at DATETIME NOT NULL,
        PRIMARY KEY (id)
    )
    """,
    "CREATE INDEX ix_execution_trade_intent_id ON execution (trade_intent_id)",
    "CREATE INDEX ix_execution_local_trade_id ON execution (local_trade_id)",
    "CREATE INDEX ix_execution_strategy_name ON execution (strategy_name)",
    "CREATE INDEX ix_execution_client_request_id ON execution (client_request_id)",
    "CREATE INDEX ix_execution_instrument ON execution (instrument)",
    "CREATE INDEX ix_execution_local_position_id ON execution (local_position_id)",
    "CREATE INDEX ix_execution_status ON execution (status)",
    "CREATE INDEX ix_execution_last_transition_at ON execution (last_transition_at)",
    "CREATE INDEX ix_execution_broker_reference ON execution (broker_reference)",
    "CREATE INDEX ix_execution_phase ON execution (phase)",
    """
    CREATE TABLE reconciliationevent (
        id INTEGER NOT NULL,
        event_type VARCHAR NOT NULL,
        trade_intent_id INTEGER,
        strategy_name VARCHAR,
        instrument VARCHAR,
        broker_reference VARCHAR,
        local_position_id INTEGER,
        details JSON,
        created_at DATETIME NOT NULL,
        PRIMARY KEY (id)
    )
    """,
    "CREATE INDEX ix_reconciliationevent_broker_reference ON reconciliationevent (broker_reference)",
    "CREATE INDEX ix_reconciliationevent_instrument ON reconciliationevent (instrument)",
    "CREATE INDEX ix_reconciliationevent_event_type ON reconciliationevent (event_type)",
    "CREATE INDEX ix_reconciliationevent_local_position_id ON reconciliationevent (local_position_id)",
    "CREATE INDEX ix_reconciliationevent_strategy_name ON reconciliationevent (strategy_name)",
    "CREATE INDEX ix_reconciliationevent_trade_intent_id ON reconciliationevent (trade_intent_id)",
    """
    CREATE TABLE tradeintent (
        id INTEGER NOT NULL,
        strategy_name VARCHAR NOT NULL,
        family_name VARCHAR,
        allocation_cycle_id VARCHAR,
        instrument VARCHAR NOT NULL,
        direction VARCHAR NOT NULL,
        state VARCHAR NOT NULL,
        signal_time DATETIME NOT NULL,
        proposed_size FLOAT,
        allocated_size FLOAT,
        proposed_risk_percent FLOAT,
        allocated_risk_percent FLOAT,
        estimated_risk_amount FLOAT,
        submitted_risk_amount FLOAT,
        fill_derived_risk_amount FLOAT,
        risk_truth_confidence VARCHAR,
        risk_currency VARCHAR,
        confidence FLOAT,
        observed_price FLOAT,
        average_fill_price FLOAT,
        filled_size FLOAT,
        broker_reference VARCHAR,
        close_broker_reference VARCHAR,
        position_id INTEGER,
        trade_id INTEGER,
        decision_reason_code VARCHAR,
        decision_reason VARCHAR,
        close_reason_code VARCHAR,
        close_reason VARCHAR,
        execution_client_request_id VARCHAR,
        market_status VARCHAR,
        tradable BOOLEAN,
        details JSON,
        submitted_at DATETIME,
        acknowledged_at DATETIME,
        completed_at DATETIME,
        opened_at DATETIME,
        closed_at DATETIME,
        created_at DATETIME NOT NULL,
        updated_at DATETIME NOT NULL,
        PRIMARY KEY (id)
    )
    """,
    "CREATE INDEX ix_tradeintent_family_name ON tradeintent (family_name)",
    "CREATE INDEX ix_tradeintent_close_broker_reference ON tradeintent (close_broker_reference)",
    "CREATE INDEX ix_tradeintent_direction ON tradeintent (direction)",
    "CREATE INDEX ix_tradeintent_execution_client_request_id ON tradeintent (execution_client_request_id)",
    "CREATE INDEX ix_tradeintent_trade_id ON tradeintent (trade_id)",
    "CREATE INDEX ix_tradeintent_position_id ON tradeintent (position_id)",
    "CREATE INDEX ix_tradeintent_broker_reference ON tradeintent (broker_reference)",
    "CREATE INDEX ix_tradeintent_decision_reason_code ON tradeintent (decision_reason_code)",
    "CREATE INDEX ix_tradeintent_instrument ON tradeintent (instrument)",
    "CREATE INDEX ix_tradeintent_close_reason_code ON tradeintent (close_reason_code)",
    "CREATE INDEX ix_tradeintent_strategy_name ON tradeintent (strategy_name)",
    "CREATE INDEX ix_tradeintent_state ON tradeintent (state)",
    "CREATE UNIQUE INDEX uq_trade_intent_active_instrument ON tradeintent (instrument) WHERE state IN ('PROPOSED', 'APPROVED', 'SUBMITTED', 'ACKNOWLEDGED', 'PARTIALLY_FILLED', 'FILLED', 'POSITION_OPENED', 'CLOSE_REQUESTED', 'EXTERNAL_POSITION_ADOPTED', 'RECOVERED_POSITION_ATTACHED')",
    "CREATE INDEX ix_tradeintent_allocation_cycle_id ON tradeintent (allocation_cycle_id)",
    """
    CREATE TABLE allocationcycle (
        id INTEGER NOT NULL,
        cycle_id VARCHAR NOT NULL,
        received_at DATETIME NOT NULL,
        completed_at DATETIME NOT NULL,
        candidate_count INTEGER NOT NULL,
        approved_count INTEGER NOT NULL,
        rejected_count INTEGER NOT NULL,
        total_requested_risk_percent FLOAT NOT NULL,
        total_allocated_risk_percent FLOAT NOT NULL,
        remaining_portfolio_risk_percent FLOAT NOT NULL,
        resized_candidate_count INTEGER NOT NULL,
        degraded_candidate_count INTEGER NOT NULL,
        blocked_unsupported_sizing_count INTEGER NOT NULL,
        blocked_approximate_live_count INTEGER NOT NULL,
        blocked_under_minimum_size_count INTEGER NOT NULL,
        blocked_budget_count INTEGER NOT NULL,
        blocked_conflict_count INTEGER NOT NULL,
        binding_budget_counts JSON,
        rejection_reason_counts JSON,
        details JSON,
        created_at DATETIME NOT NULL,
        PRIMARY KEY (id)
    )
    """,
    "CREATE INDEX ix_allocationcycle_received_at_desc ON allocationcycle (received_at DESC)",
    "CREATE INDEX ix_allocationcycle_received_at ON allocationcycle (received_at)",
    "CREATE INDEX ix_allocationcycle_completed_at ON allocationcycle (completed_at)",
    "CREATE UNIQUE INDEX ix_allocationcycle_cycle_id ON allocationcycle (cycle_id)",
    """
    CREATE TABLE watchlist_entry (
        id INTEGER NOT NULL,
        instrument VARCHAR NOT NULL,
        tier VARCHAR NOT NULL,
        status VARCHAR NOT NULL,
        asset_class VARCHAR,
        pinned BOOLEAN NOT NULL,
        reason VARCHAR,
        priority_score FLOAT NOT NULL,
        requested_frequency VARCHAR,
        assigned_at DATETIME NOT NULL,
        min_residency_until DATETIME,
        cooldown_until DATETIME,
        promotion_expires_at DATETIME,
        last_streamed_at DATETIME,
        last_refreshed_at DATETIME,
        updated_at DATETIME NOT NULL,
        PRIMARY KEY (id)
    )
    """,
    "CREATE INDEX ix_watchlist_entry_pinned ON watchlist_entry (pinned)",
    "CREATE INDEX ix_watchlist_entry_tier_status_priority ON watchlist_entry (tier, status, pinned DESC, priority_score DESC, assigned_at ASC)",
    "CREATE INDEX ix_watchlist_entry_asset_class ON watchlist_entry (asset_class)",
    "CREATE INDEX ix_watchlist_entry_tier ON watchlist_entry (tier)",
    "CREATE INDEX ix_watchlist_entry_status ON watchlist_entry (status)",
    "CREATE INDEX ix_watchlist_entry_instrument ON watchlist_entry (instrument)",
    """
    CREATE TABLE operator_shortlist_entry (
        id INTEGER NOT NULL,
        instrument VARCHAR NOT NULL,
        actor_id VARCHAR NOT NULL,
        note VARCHAR,
        created_at DATETIME NOT NULL,
        updated_at DATETIME NOT NULL,
        PRIMARY KEY (id)
    )
    """,
    "CREATE UNIQUE INDEX ix_operator_shortlist_entry_instrument ON operator_shortlist_entry (instrument)",
    "CREATE INDEX ix_operator_shortlist_entry_actor_id ON operator_shortlist_entry (actor_id)",
    """
    CREATE TABLE runtimelease (
        lease_name VARCHAR NOT NULL,
        owner_id VARCHAR NOT NULL,
        acquired_at DATETIME NOT NULL,
        heartbeat_at DATETIME NOT NULL,
        expires_at DATETIME NOT NULL,
        released_at DATETIME,
        PRIMARY KEY (lease_name)
    )
    """,
    "CREATE INDEX ix_runtimelease_released_at ON runtimelease (released_at)",
    "CREATE INDEX ix_runtimelease_expires_at ON runtimelease (expires_at)",
    "CREATE INDEX ix_runtimelease_owner_expires ON runtimelease (owner_id, expires_at DESC)",
    "CREATE INDEX ix_runtimelease_owner_id ON runtimelease (owner_id)",
)

DOWNGRADE_TABLES = (
    "runtimelease",
    "operator_shortlist_entry",
    "watchlist_entry",
    "allocationcycle",
    "tradeintent",
    "reconciliationevent",
    "execution",
    "position",
    "trade",
    "strategyruntimestate",
    "strategyfamilygovernance",
    "strategydeployment",
    "generatedreviewrecord",
    "promotion_request",
    "operatorcontrolstate",
    "domain_events",
    "allocationalert",
)


def upgrade() -> None:
    for statement in UPGRADE_STATEMENTS:
        op.execute(statement)


def downgrade() -> None:
    for table_name in DOWNGRADE_TABLES:
        op.execute(f"DROP TABLE IF EXISTS {table_name}")
