from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True, slots=True)
class InstrumentDefinition:
    epic: str
    label: str
    category: str
    symbol: str
    activity_level: str
    compatible_strategies: tuple[str, ...]
    reference_price: float


INSTRUMENT_CATALOG: tuple[InstrumentDefinition, ...] = (
    InstrumentDefinition(
        epic="CS.D.EURUSD.CFD.IP",
        label="EUR/USD",
        category="FOREX",
        symbol="EURUSD",
        activity_level="HIGH",
        compatible_strategies=("Mean reversion", "Breakout guard", "Carry drift"),
        reference_price=1.0842,
    ),
    InstrumentDefinition(
        epic="CS.D.GBPUSD.CFD.IP",
        label="GBP/USD",
        category="FOREX",
        symbol="GBPUSD",
        activity_level="HIGH",
        compatible_strategies=("Breakout guard", "Session momentum"),
        reference_price=1.2928,
    ),
    InstrumentDefinition(
        epic="CS.D.USDJPY.CFD.IP",
        label="USD/JPY",
        category="FOREX",
        symbol="USDJPY",
        activity_level="MEDIUM",
        compatible_strategies=("Carry drift", "Session momentum"),
        reference_price=149.82,
    ),
    InstrumentDefinition(
        epic="CS.D.AUDUSD.CFD.IP",
        label="AUD/USD",
        category="FOREX",
        symbol="AUDUSD",
        activity_level="MEDIUM",
        compatible_strategies=("Mean reversion", "Carry drift"),
        reference_price=0.6592,
    ),
    InstrumentDefinition(
        epic="CS.D.USDCHF.CFD.IP",
        label="USD/CHF",
        category="FOREX",
        symbol="USDCHF",
        activity_level="LOW",
        compatible_strategies=("Carry drift",),
        reference_price=0.8824,
    ),
    InstrumentDefinition(
        epic="CS.D.USDCAD.CFD.IP",
        label="USD/CAD",
        category="FOREX",
        symbol="USDCAD",
        activity_level="LOW",
        compatible_strategies=("Carry drift",),
        reference_price=1.3529,
    ),
    InstrumentDefinition(
        epic="CS.D.EURGBP.CFD.IP",
        label="EUR/GBP",
        category="FOREX",
        symbol="EURGBP",
        activity_level="LOW",
        compatible_strategies=("Mean reversion",),
        reference_price=0.8384,
    ),
    InstrumentDefinition(
        epic="CS.D.EURJPY.CFD.IP",
        label="EUR/JPY",
        category="FOREX",
        symbol="EURJPY",
        activity_level="HIGH",
        compatible_strategies=("Breakout guard", "Carry drift"),
        reference_price=162.44,
    ),
    InstrumentDefinition(
        epic="CS.D.GBPJPY.CFD.IP",
        label="GBP/JPY",
        category="FOREX",
        symbol="GBPJPY",
        activity_level="HIGH",
        compatible_strategies=("Breakout guard", "Session momentum"),
        reference_price=193.72,
    ),
    InstrumentDefinition(
        epic="CS.D.EURAUD.CFD.IP",
        label="EUR/AUD",
        category="FOREX",
        symbol="EURAUD",
        activity_level="MEDIUM",
        compatible_strategies=("Mean reversion", "Carry drift"),
        reference_price=1.6448,
    ),
    InstrumentDefinition(
        epic="CS.D.NZDUSD.CFD.IP",
        label="NZD/USD",
        category="FOREX",
        symbol="NZDUSD",
        activity_level="MEDIUM",
        compatible_strategies=("Mean reversion", "Session momentum"),
        reference_price=0.6112,
    ),
    InstrumentDefinition(
        epic="CS.D.EURNZD.CFD.IP",
        label="EUR/NZD",
        category="FOREX",
        symbol="EURNZD",
        activity_level="LOW",
        compatible_strategies=("Carry drift",),
        reference_price=1.7741,
    ),
    InstrumentDefinition(
        epic="CS.D.GBPAUD.CFD.IP",
        label="GBP/AUD",
        category="FOREX",
        symbol="GBPAUD",
        activity_level="MEDIUM",
        compatible_strategies=("Breakout guard", "Carry drift"),
        reference_price=1.9615,
    ),
    InstrumentDefinition(
        epic="CS.D.EURCAD.CFD.IP",
        label="EUR/CAD",
        category="FOREX",
        symbol="EURCAD",
        activity_level="LOW",
        compatible_strategies=("Mean reversion",),
        reference_price=1.4672,
    ),
    InstrumentDefinition(
        epic="CS.D.CADJPY.CFD.IP",
        label="CAD/JPY",
        category="FOREX",
        symbol="CADJPY",
        activity_level="MEDIUM",
        compatible_strategies=("Carry drift", "Session momentum"),
        reference_price=110.84,
    ),
    InstrumentDefinition(
        epic="IX.D.FTSE.DAILY.IP",
        label="FTSE 100",
        category="INDICES",
        symbol="UKX",
        activity_level="MEDIUM",
        compatible_strategies=("Mean reversion", "Breakout guard"),
        reference_price=8178.4,
    ),
    InstrumentDefinition(
        epic="IX.D.DAX.DAILY.IP",
        label="DAX 40",
        category="INDICES",
        symbol="DAX",
        activity_level="MEDIUM",
        compatible_strategies=("Carry drift", "Mean reversion"),
        reference_price=18492.6,
    ),
    InstrumentDefinition(
        epic="IX.D.NASDAQ.DAILY.IP",
        label="Nasdaq 100",
        category="INDICES",
        symbol="NDX",
        activity_level="HIGH",
        compatible_strategies=("Breakout guard", "Trend follow"),
        reference_price=18864.1,
    ),
    InstrumentDefinition(
        epic="IX.D.SP500.DAILY.IP",
        label="S&P 500",
        category="INDICES",
        symbol="SPX",
        activity_level="HIGH",
        compatible_strategies=("Breakout guard", "Mean reversion"),
        reference_price=5242.8,
    ),
    InstrumentDefinition(
        epic="IX.D.DOW.DAILY.IP",
        label="Wall Street",
        category="INDICES",
        symbol="DJI",
        activity_level="HIGH",
        compatible_strategies=("Trend follow", "Breakout guard"),
        reference_price=39862.4,
    ),
    InstrumentDefinition(
        epic="IX.D.NIKKEI.DAILY.IP",
        label="Nikkei 225",
        category="INDICES",
        symbol="NI225",
        activity_level="MEDIUM",
        compatible_strategies=("Overnight drift", "Breakout guard"),
        reference_price=39742.6,
    ),
    InstrumentDefinition(
        epic="IX.D.CAC.DAILY.IP",
        label="CAC 40",
        category="INDICES",
        symbol="CAC",
        activity_level="MEDIUM",
        compatible_strategies=("Mean reversion",),
        reference_price=8214.8,
    ),
    InstrumentDefinition(
        epic="IX.D.HANGSENG.DAILY.IP",
        label="Hang Seng",
        category="INDICES",
        symbol="HSI",
        activity_level="MEDIUM",
        compatible_strategies=("Overnight drift",),
        reference_price=16784.3,
    ),
    InstrumentDefinition(
        epic="COM.D.XAUUSD.CFD.IP",
        label="Gold",
        category="COMMODITIES",
        symbol="XAUUSD",
        activity_level="HIGH",
        compatible_strategies=("Breakout guard", "Volatility fade"),
        reference_price=2184.6,
    ),
    InstrumentDefinition(
        epic="COM.D.CL.CFD.IP",
        label="WTI Crude",
        category="COMMODITIES",
        symbol="CL",
        activity_level="MEDIUM",
        compatible_strategies=("Trend follow", "Breakout guard"),
        reference_price=81.42,
    ),
    InstrumentDefinition(
        epic="COM.D.XAGUSD.CFD.IP",
        label="Silver",
        category="COMMODITIES",
        symbol="XAGUSD",
        activity_level="LOW",
        compatible_strategies=("Mean reversion",),
        reference_price=24.31,
    ),
    InstrumentDefinition(
        epic="COM.D.NG.CFD.IP",
        label="Natural Gas",
        category="COMMODITIES",
        symbol="NG",
        activity_level="HIGH",
        compatible_strategies=("Volatility fade", "Breakout guard"),
        reference_price=1.84,
    ),
    InstrumentDefinition(
        epic="COM.D.CU.CFD.IP",
        label="Copper",
        category="COMMODITIES",
        symbol="COPPER",
        activity_level="MEDIUM",
        compatible_strategies=("Trend follow",),
        reference_price=4.06,
    ),
    InstrumentDefinition(
        epic="COM.D.BRENT.CFD.IP",
        label="Brent Crude",
        category="COMMODITIES",
        symbol="BRENT",
        activity_level="MEDIUM",
        compatible_strategies=("Trend follow", "Breakout guard"),
        reference_price=85.18,
    ),
    InstrumentDefinition(
        epic="STK.D.AAPL.CFD.IP",
        label="Apple",
        category="STOCKS",
        symbol="AAPL",
        activity_level="HIGH",
        compatible_strategies=("Opening impulse", "Mean reversion"),
        reference_price=214.82,
    ),
    InstrumentDefinition(
        epic="STK.D.MSFT.CFD.IP",
        label="Microsoft",
        category="STOCKS",
        symbol="MSFT",
        activity_level="MEDIUM",
        compatible_strategies=("Trend follow", "Breakout guard"),
        reference_price=428.17,
    ),
    InstrumentDefinition(
        epic="STK.D.TSLA.CFD.IP",
        label="Tesla",
        category="STOCKS",
        symbol="TSLA",
        activity_level="HIGH",
        compatible_strategies=("Volatility breakout",),
        reference_price=173.94,
    ),
    InstrumentDefinition(
        epic="STK.D.NVDA.CFD.IP",
        label="NVIDIA",
        category="STOCKS",
        symbol="NVDA",
        activity_level="HIGH",
        compatible_strategies=("Trend follow", "Opening impulse"),
        reference_price=903.56,
    ),
    InstrumentDefinition(
        epic="STK.D.AMZN.CFD.IP",
        label="Amazon",
        category="STOCKS",
        symbol="AMZN",
        activity_level="HIGH",
        compatible_strategies=("Breakout guard", "Mean reversion"),
        reference_price=182.41,
    ),
    InstrumentDefinition(
        epic="STK.D.META.CFD.IP",
        label="Meta",
        category="STOCKS",
        symbol="META",
        activity_level="MEDIUM",
        compatible_strategies=("Trend follow",),
        reference_price=498.84,
    ),
    InstrumentDefinition(
        epic="STK.D.GOOGL.CFD.IP",
        label="Alphabet",
        category="STOCKS",
        symbol="GOOGL",
        activity_level="MEDIUM",
        compatible_strategies=("Mean reversion", "Breakout guard"),
        reference_price=153.62,
    ),
    InstrumentDefinition(
        epic="STK.D.AMD.CFD.IP",
        label="AMD",
        category="STOCKS",
        symbol="AMD",
        activity_level="HIGH",
        compatible_strategies=("Volatility breakout", "Trend follow"),
        reference_price=176.48,
    ),
    InstrumentDefinition(
        epic="CRYPTO.D.BTCUSD.CFD.IP",
        label="Bitcoin",
        category="CRYPTO",
        symbol="BTCUSD",
        activity_level="HIGH",
        compatible_strategies=("Trend follow", "Breakout guard", "Funding arb"),
        reference_price=68242.0,
    ),
    InstrumentDefinition(
        epic="CRYPTO.D.ETHUSD.CFD.IP",
        label="Ethereum",
        category="CRYPTO",
        symbol="ETHUSD",
        activity_level="HIGH",
        compatible_strategies=("Mean reversion", "Funding arb"),
        reference_price=3648.2,
    ),
    InstrumentDefinition(
        epic="CRYPTO.D.SOLUSD.CFD.IP",
        label="Solana",
        category="CRYPTO",
        symbol="SOLUSD",
        activity_level="MEDIUM",
        compatible_strategies=("Momentum burst",),
        reference_price=168.31,
    ),
    InstrumentDefinition(
        epic="CRYPTO.D.XRPUSD.CFD.IP",
        label="XRP",
        category="CRYPTO",
        symbol="XRPUSD",
        activity_level="MEDIUM",
        compatible_strategies=("Mean reversion", "Momentum burst"),
        reference_price=0.6124,
    ),
    InstrumentDefinition(
        epic="CRYPTO.D.ADAUSD.CFD.IP",
        label="Cardano",
        category="CRYPTO",
        symbol="ADAUSD",
        activity_level="LOW",
        compatible_strategies=("Mean reversion",),
        reference_price=0.7248,
    ),
    InstrumentDefinition(
        epic="CRYPTO.D.DOGUSD.CFD.IP",
        label="Dogecoin",
        category="CRYPTO",
        symbol="DOGEUSD",
        activity_level="HIGH",
        compatible_strategies=("Momentum burst", "Volatility breakout"),
        reference_price=0.1482,
    ),
)


def list_instruments() -> list[dict[str, str]]:
    return [{"epic": instrument.epic, "label": instrument.label, "category": instrument.category} for instrument in INSTRUMENT_CATALOG]


def list_market_instruments() -> list[InstrumentDefinition]:
    return list(INSTRUMENT_CATALOG)
