from __future__ import annotations

from enum import Enum


class RiskTruthConfidence(str, Enum):
    EXACT_FILL_DERIVED = "EXACT_FILL_DERIVED"
    BROKER_CONFIRMED_AVERAGE_FILL_ESTIMATED = "BROKER_CONFIRMED_AVERAGE_FILL_ESTIMATED"
    PARTIAL_FILL_PROVISIONAL = "PARTIAL_FILL_PROVISIONAL"
    SUBMITTED_EXECUTABLE_ESTIMATE = "SUBMITTED_EXECUTABLE_ESTIMATE"
    ALLOCATION_INTENT_ONLY = "ALLOCATION_INTENT_ONLY"
    INCOMPLETE_DEGRADED = "INCOMPLETE_DEGRADED"
    SIMULATED_LOCAL_FILL = "SIMULATED_LOCAL_FILL"
    UNKNOWN = "UNKNOWN"


RISK_TRUTH_CONFIDENCE_VALUES = tuple(
    confidence.value for confidence in RiskTruthConfidence
)
